"""Weak segmentation-mask labels generated by buffering catalog polylines,
in place of DBR-Net's hand-labeled pixel masks -- this project has no
hand-labeled ridge masks (see research/arm_c_deep_learning/SPEC.md's
confounds section: this is a real, documented supervision-quality gap, not
a substitute claimed to be equivalent).
"""
from __future__ import annotations

from typing import List, Tuple

import numpy as np
from skimage.draw import line as draw_line
from skimage.morphology import dilation, disk

DEFAULT_HALF_WIDTH_PX = 18  # ~3.47km average ridge width (Thompson et al. 2017
# global mean) at 100m/px GLD100 resolution -> ~35px width -> ~18px half-width.
# A single global default, not per-ridge -- real ridges vary, see SPEC.md.


def polyline_to_mask(
    shape: Tuple[int, int],
    pixel_points: List[Tuple[float, float]],
    half_width_px: int = DEFAULT_HALF_WIDTH_PX,
) -> np.ndarray:
    """Rasterize a polyline (list of (row, col) pixel coordinates, e.g. from
    rasterio.transform.rowcol on the catalog's lon/lat vertices) into a
    binary mask, then dilate by half_width_px to approximate the ridge's
    actual footprint from its centerline.
    """
    mask = np.zeros(shape, dtype=bool)
    rows, cols = shape

    for (r0, c0), (r1, c1) in zip(pixel_points[:-1], pixel_points[1:]):
        rr, cc = draw_line(int(round(r0)), int(round(c0)), int(round(r1)), int(round(c1)))
        valid = (rr >= 0) & (rr < rows) & (cc >= 0) & (cc < cols)
        mask[rr[valid], cc[valid]] = True

    if half_width_px > 0:
        mask = dilation(mask, disk(half_width_px))

    return mask
